#! /bin/sh

### Remove me before distributing the library FIXME

find ./ -name '*~' | xargs rm
rm -rf ./config.status
rm -rf ./config.log
rm -rf ./config.h
rm -rf ./configure.scan
rm -rf ./autoscan.log
rm -rf ./autom4te.cache
rm -rf ./Makefile

rm -rf ./build/libsunbathe.a
rm -rf ./build/libsunbathe.so
rm -rf ./build/run_bench
rm -rf ./build/run_test

